import Filter from '@/components/Filter'
import Navbar from '@/components/Navbar'
import Pagenation from '@/components/Pagination'
import Tour from '@/components/Tour'
import Head from 'next/head'
import { useContext, useEffect, useState } from 'react'
import clientPromise from '../../lib/mongodb'
import { Context } from './_app'

export default function Explore({ tours }) {
  const { SETTOURS } = useContext(Context)
  const [loading, setLoading] = useState(false)
  SETTOURS(tours)

  return (
    <>
      <Head>
        <title>Uzbekistan Tours</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className='explore pb-4'>
        <div className='bg-sky-950 sticky top-0 z-50'>
          <Navbar />
        </div>
        <div className='flex max-w-1440 mx-auto mt-4'>
          <div className='w-[50vw]'>
            <Filter params={{ loading, setLoading }} />
          </div>
          {loading ?
            <div className='w-[200vw] flex items-center justify-center'>
              <div class="lds-ring">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
              </div>
            </div>
            : <div className='w-[200vw] h-screen overflow-auto pb-32'>
              <Pagenation tours={tours} />
            </div>}
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  try {
    const client = await clientPromise;
    const db = client.db("test");

    const tours = await db
      .collection("tours")
      .find({})
      .toArray();

    return {
      props: { tours: JSON.parse(JSON.stringify(tours)) },
    };
  } catch (e) {
    console.error(e);
    return {
      props: { tours: ['nodata'] },
    };
  }
}