import Filter from '@/components/Filter'
import Navbar from '@/components/Navbar'
import Tour from '@/components/Tour'
import Head from 'next/head'
import { useContext, useEffect } from 'react'
import clientPromise from '../../lib/mongodb'
import { Context } from './_app'

export default function Explore({ tours }) {
  const { SETTOURS, filteredTours } = useContext(Context)
  SETTOURS(tours)

  useEffect(() => {
    console.log(filteredTours)
  }, [filteredTours])

  return (
    <>
      <Head>
        <title>Uzbekistan Tours</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main>
        <div className='bg-sky-950'>
          <Navbar />
        </div>
        <div className='flex max-w-1440 mx-auto mt-4'>
          <div className='w-[50vw]'>
            <Filter />
          </div>
          <div className="grid grid-cols-4 gap-4 mx-6 mt-10 w-[200vw]">
            {filteredTours?.length ?
              filteredTours.map(tour => {
                return <Tour
                  key={tour.title}
                  title={tour.title}
                  imgSrc={tour.image}
                  href={tour.link}
                  desc={tour.desc}
                  price={tour.price}
                />
              })
              : filteredTours?.length == 0
                ?
                <h1 className='text-center font-semibold text-2xl'>No Data Found :(</h1>
                : tours.map(tour => {
                  return <Tour
                    key={tour.title}
                    title={tour.title}
                    imgSrc={tour.image}
                    href={tour.link}
                    desc={tour.desc}
                    price={tour.price}
                  />
                })}
          </div>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  try {
    const client = await clientPromise;
    const db = client.db("test");

    const tours = await db
      .collection("tours")
      .find({})
      .toArray();

    return {
      props: { tours: JSON.parse(JSON.stringify(tours)) },
    };
  } catch (e) {
    console.error(e);
    return {
      props: { tours: [] },
    };
  }
}