import Tour from '@/components/Tour';
import axios from 'axios';
import Head from 'next/head'
import { useEffect, useState } from 'react';
import Navbar from './../components/Navbar'

export default function Home() {
  const [tours, setTours] = useState()
  useEffect(() => {
    const tours = axios.get(`http://localhost:3000/api/tours`).then(res => {
      setTours(res.data)
    })
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className="grid grid-cols-4 gap-4 mx-20 mt-10">
          {tours?.map(tour => {
            return <Tour
              title={tour.title}
              imgSrc={tour.image}
              href={tour.link}
              desc={tour.desc}
              price={tour.price}
            />
          })}
        </div>
      </main>
    </>
  )
}