import Tour from '@/components/Tour';
import Head from 'next/head'
import { useContext } from 'react';
import clientPromise from '../../lib/mongodb';
import Navbar from './../components/Navbar'
import { Context } from './_app';

export default function Home({ tours }) {
  const { SETTOURS, filteredTours } = useContext(Context)
  console.log(filteredTours)
  SETTOURS(tours)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className="grid grid-cols-4 gap-4 px-10 mt-10 max-w-1440 mx-auto">
          {filteredTours?.length ?
            filteredTours.map(tour => {
              return <Tour
                key={tour.title}
                title={tour.title}
                imgSrc={tour.image}
                href={tour.link}
                desc={tour.desc}
                price={tour.price}
              />
            })
            : filteredTours?.length == 0
              ?
              <h1>No Data Found</h1>
              : tours.map(tour => {
                return <Tour
                  key={tour.title}
                  title={tour.title}
                  imgSrc={tour.image}
                  href={tour.link}
                  desc={tour.desc}
                  price={tour.price}
                />
              })}
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  try {
    const client = await clientPromise;
    const db = client.db("test");

    const tours = await db
      .collection("tours")
      .find({})
      .toArray();

    return {
      props: { tours: JSON.parse(JSON.stringify(tours)) },
    };
  } catch (e) {
    console.error(e);
  }
}