import Header from '@/components/Header';
import Pagenation from '@/components/Pagination';
import Head from 'next/head'
import { useContext, useEffect } from 'react';
import clientPromise from '../../lib/mongodb';
import Navbar from './../components/Navbar'
import { Context } from './_app';

export default function Home({ tours }) {
  const { SETTOURS, setFilteredTours } = useContext(Context)
  useEffect(() => {
    SETTOURS(tours)
  }, [])
  return (
    <>
      <Head>
        <title>Uzbekistan Tours</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/logo.png" />
      </Head>
      <main>
        <Navbar />
        <Header />
        <Pagenation tours={tours} />
      </main>
    </>
  )
}

export async function getServerSideProps() {
  try {
    const client = await clientPromise;
    const db = client.db("test");

    const tours = await db
      .collection("tours")
      .find({})
      .toArray();

    return {
      props: { tours: JSON.parse(JSON.stringify(tours)) },
    };
  } catch (e) {
    console.error(e);
    return {
      props: { tours: [] }
    }
  }
}